In [30]:
import numpy as np
import datetime as datetime
from geopack import geopack

Load IGRF coefficients ...


In [3]:
#open meanp.npy
meanp = np.load('meanp.npy')
meanp.shape

(2400,)

In [31]:
flearn=1e-6 #for pot and fac
#data_d = datpcap*flearn #output data

nsteps=45792 #159 days * 24 hours* 12 (5min steps)

def read_sw_data(file_name):
    dataa = np.empty(0)
    datab = np.empty(0)
    datac = np.empty(0)
    datad = np.empty(0)
    datae = np.empty(0)
    dataf = np.empty(0)
    datag = np.empty(0)
    datah = np.empty(0)

    with open(file_name, 'r') as f:
        lines = f.readlines()
        for line in lines:
            tmp = line.split()
            dataa = np.hstack((dataa, float(tmp[0])))  # yy
            datab = np.hstack((datab, float(tmp[1])))  # mm
            datac = np.hstack((datac, float(tmp[2])))  # dd
            datad = np.hstack((datad, float(tmp[3])))  # hh
            datae = np.hstack((datae, float(tmp[4])))  # by
            dataf = np.hstack((dataf, float(tmp[5])))  # bz
            datag = np.hstack((datag, float(tmp[6])))  # log10v-2.5
            datah = np.hstack((datah, float(tmp[7])))  # log10n-1.0

    return dataa,datab,datac,datad,datae,dataf,datag,datah

yy,mm,dd,hh,sw1,sw2,sw3,sw4 = read_sw_data(file_name='swall3_5min.txt') #y,m,d,h, by,bz,v,n


t0 = datetime.datetime(1970,1,1)
psarr=np.zeros(nsteps) # dipole tilt angle

for ii in range(0,nsteps):
     mn=60.0*(hh[ii]-int(hh[ii]))
     t1 = datetime.datetime(int(yy[ii]),int(mm[ii]),int(dd[ii]),int(hh[ii]),int(mn),0)
     ut = (t1-t0).total_seconds()
     ps = geopack.recalc(ut)
     psarr[ii]=ps

all0 = np.vstack((psarr,sw1,sw2,sw3,sw4))

In [35]:
psarr

array([0.25681747, 0.25288916, 0.24964707, ..., 0.2764643 , 0.27306385,
       0.2696846 ])

In [19]:
with open('swall3_5min.txt', 'r') as f:
    lines = f.readlines()
    for line in lines:
        tmp = line.split()
        print(tmp)
        break
lines

['2021.00', '5.000000', '11.000000', '0.033333', '1.140000', '0.484000', '0.023041', '0.048442']


['   2021.00   5.000000  11.000000   0.033333   1.140000   0.484000   0.023041   0.048442\n',
 '   2021.00   5.000000  11.000000   0.116667   1.120000   1.560000   0.018121  -0.018997\n',
 '   2021.00   5.000000  11.000000   0.200000   0.880000   0.136000   0.017602  -0.012334\n',
 '   2021.00   5.000000  11.000000   0.283333   0.340000  -0.306000   0.014646  -0.042393\n',
 '   2021.00   5.000000  11.000000   0.366667  -0.680000  -0.674000   0.017069  -0.037441\n',
 '   2021.00   5.000000  11.000000   0.450000   2.100000  -0.584000   0.022583  -0.028724\n',
 '   2021.00   5.000000  11.000000   0.533333   2.400000   0.058000   0.024687  -0.026872\n',
 '   2021.00   5.000000  11.000000   0.616667   2.280000   0.720000   0.025734  -0.030584\n',
 '   2021.00   5.000000  11.000000   0.700000   2.260000   0.434000   0.025941  -0.031517\n',
 '   2021.00   5.000000  11.000000   0.783333   2.520000   0.666000   0.025280  -0.043639\n',
 '   2021.00   5.000000  11.000000   0.866667  -1.200000  -0

In [25]:
import pandas as pd

col_names = ['yr','mm','dd','hh','by','bz','v','n']
sw = pd.read_csv('swall3_5min.txt', sep='  ', header=None, skiprows=10081, names=col_names)
sw

/var/folders/n2/t9qn3_vj3nd6jb505jq_l8dw0000gn/T/ipykernel_22880/4170953645.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  sw = pd.read_csv('swall3_5min.txt', sep='  ', header=None, skiprows=10081, names=col_names)


yr   mm    dd         hh         by     bz         v         n
0      2022.0  2.0   2.0   0.116667  10.420000  4.412  0.144917  0.146996
1      2022.0  2.0   2.0   0.200000   8.180000  7.534  0.138410  0.169322
2      2022.0  2.0   2.0   0.283333   8.980000  6.720  0.139068  0.136086
3      2022.0  2.0   2.0   0.366667   8.200000  5.618  0.138336  0.120047
4      2022.0  2.0   2.0   0.450000  11.440000  2.222  0.146786  0.127494
...       ...  ...   ...        ...        ...    ...       ...       ...
35706  2022.0  7.0  31.0  23.616667   2.320000  3.520  0.184475  0.044069
35707  2022.0  7.0  31.0  23.700001  -0.460000  3.418  0.181397  0.017200
35708  2022.0  7.0  31.0  23.783335  -5.380000  4.378  0.175126 -0.024844
35709  2022.0  7.0  31.0  23.866667  -5.800000  3.816  0.178249 -0.026687
35710  2022.0  7.0  31.0  23.950001  -4.280000  4.768  0.170147 -0.054728

[35711 rows x 8 columns]

In [43]:
lat = np.linspace(53.109, 89.739, 30)
lon = np.linspace(0,360,80)
lat, lon

(array([53.109     , 54.37210345, 55.6352069 , 56.89831034, 58.16141379,
        59.42451724, 60.68762069, 61.95072414, 63.21382759, 64.47693103,
        65.74003448, 67.00313793, 68.26624138, 69.52934483, 70.79244828,
        72.05555172, 73.31865517, 74.58175862, 75.84486207, 77.10796552,
        78.37106897, 79.63417241, 80.89727586, 82.16037931, 83.42348276,
        84.68658621, 85.94968966, 87.2127931 , 88.47589655, 89.739     ]),
 array([  0.        ,   4.55696203,   9.11392405,  13.67088608,
         18.2278481 ,  22.78481013,  27.34177215,  31.89873418,
         36.4556962 ,  41.01265823,  45.56962025,  50.12658228,
         54.6835443 ,  59.24050633,  63.79746835,  68.35443038,
         72.91139241,  77.46835443,  82.02531646,  86.58227848,
         91.13924051,  95.69620253, 100.25316456, 104.81012658,
        109.36708861, 113.92405063, 118.48101266, 123.03797468,
        127.59493671, 132.15189873, 136.70886076, 141.26582278,
        145.82278481, 150.37974684, 154.93670886